### ISSUE TITLE
一些我认为美中不足的地方

### ISSUE THREAD

**Issue by FroyoCatOSS** [STBBRD/ZongziTEK-Blackboard-Sticker#1]
小黑板用着不错，但可能有些地方还需要改进：
1.启动台建议可以多加几个常用的应用，或者直接做个“添加应用”的选项，有些老师不只用的希沃白板，还有GeoGebra5,其他品牌的一些白班软件等等。
2.课程表是件好事，但“编辑课程表”里的课程过多的话就会显示不下，建议加个换行。
3.我觉得还是建议弄个关闭按钮吧，这个似乎只能在任务管理器里结束进程，不然有些老师想关闭还得请教电教委(笑
![image](https://user-images.githubusercontent.com/106894604/218300377-efa4acfa-19ea-4384-bfe7-078c66936b41.png)
![image](https://user-images.githubusercontent.com/106894604/218300389-ea2b9e96-1c4e-4bd4-90e8-14547b97a8c2.png)
我在Windows11 22h2 x64是显示这样的，一些白板还在用着win10的老版本，比如说1809,1709,甚至win7
不清楚这些系统上的运行表现如何（qwq
最后祝这个小项目越来越好吧）

**Comment by STBBRD** [comment]
自定义启动台正在开发，以后会有

这个窗口不置顶，不影响上课，因为我怕晚自习时候有人偷偷关掉了，看不了小黑板里的作业，所以没加关闭窗口按钮
编辑课程表里的文本框是可以回车换行的

**Comment by STBBRD** [comment]
目前自定义启动台功能已经有了

https://github.com/STBBRD/ZongziTEK-Blackboard-Sticker/releases/latest
