### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by Ry4nnnnn** [STBBRD/ZongziTEK-Blackboard-Sticker#14]
## 非常好用，感谢作者，另外希望作者可以更新几个功能
1.**希望当前课程能够高亮显示**（_或者自定义颜色_），**已经上过的课程灰字显示**（_或者自定义颜色_）。
2.**支持自动/手动在上 下午课程之间添加分隔符**。
3.**支持自主更换字体，字体大小**（_我们班电脑字体过小，通过调整缩放倍率会导致主面板过宽_）**以及配色**（_配色包括字体以及背景_）。
4.**启动台可以隐藏**。
5.**简洁模式下也可以显示倒计时/日期/天气**。

**Comment by STBBRD** [comment]
将采纳部分建议

**Comment by STBBRD** [comment]
隐藏启动台不会考虑。为了防止你的启动台被希沃管家助手遮挡，可以在 Actions 中下载最新预览版，开启设置中的 “隐藏希沃管家助手”

**Comment by Ry4nnnnn** [comment]
> 将采纳部分建议

能麻烦问下是哪几条吗
