### ISSUE TITLE
黑板贴异常关闭

### ISSUE THREAD

**Issue by dargoncat** [STBBRD/ZongziTEK-Blackboard-Sticker#16]
在黑板贴启动较长的一段时间后，有概率抛出一个未处理的异常，目前无稳定复现方法

**Comment by STBBRD** [comment]
是最新 Release 还是某一个预览版

**Comment by dargoncat** [comment]
直接从仓库的actions里面提的预览版



在 2024-04-13 20:53:11，"ZongziTEK" ***@***.***> 写道：

是最新 Release 还是某一个预览版

**Comment by STBBRD** [comment]
用的是什么系统

**Comment by dargoncat** [comment]
> 用的是什么系统

win10啊

**Comment by STBBRD** [comment]
要不把你的 Settings.json 发过来，我看看能不能复现

**Comment by dargoncat** [comment]
[Settings.json](https://github.com/STBBRD/ZongziTEK-Blackboard-Sticker/files/15047488/Settings.json)

**Comment by dargoncat** [comment]
算了，复现不了就不管了，反正重启一下就行
