### ISSUE TITLE
调节总体高度

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [STBBRD/ZongziTEK-Blackboard-Sticker#22]
一般我们这里的保守派还是喜欢在 [ClassIsland](https://github.com/ClassIsland/ClassIsland) 上的课表，所以上面可不可以有选择性的空出一段（长度可调），把置底的 ClassIsland 显示出来

**Comment by STBBRD** [comment]
请把 ClassIsland 调整到屏幕左上角 。
