### ISSUE TITLE
“课程表”支持偏移时间量

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [STBBRD/ZongziTEK-Blackboard-Sticker#23]
课表不支持时间调节（偏移时间量），我们学校这个铃慢整整44秒多（改系统时间太麻烦）
可否添加一个“时间偏移量”，实现整体移动秒数？

**Comment by STBBRD** [comment]
可以使用 ClassIsland，并关闭黑板贴的上下课提醒

**Comment by Qsgz2023ji5ban** [comment]
很好，自己手搓了一个

我们同学下个学期要用，只好让我这个懂一点Py和VB的人搞了

#25 自己搓的，应该会被嫌弃

**Comment by STBBRD** [comment]
做完了
