### ISSUE TITLE
CI 安装 .NET Core 过程似乎是多余的

### ISSUE THREAD

**Issue by lindexi** [STBBRD/ZongziTEK-Blackboard-Sticker#3]
项目是采用 .NET Framework 4.7.2 框架的，看起来可以不需要安装 .NET 6 负载。去掉安装可以提升构建速度

感觉下面的代码可以去掉

https://github.com/STBBRD/ZongziTEK-Blackboard-Sticker/blob/3096671f6fbf2c235203bfc95463fbbc91f99cb0/.github/workflows/main.yml#L20C7-L24

**Comment by STBBRD** [comment]
修改好了
