### ISSUE TITLE
上下课提醒时间补偿数值设置

### ISSUE THREAD

**Issue by quiet-star-gazing** [STBBRD/ZongziTEK-Blackboard-Sticker#31]
上下课提醒时间补偿数值设置无法超过-30s
修改settings.json文件少于-30无法进行提示

**Comment by STBBRD** [comment]
再大 Slider 就太难操作了，建议与学校沟通，让学校校准铃声时间

**Comment by quiet-star-gazing** [comment]
我描述的有点问题，就是提前打预备铃的时候就提醒上课信息

**Comment by MKStoler4096** [comment]
> 再大 Slider 就太难操作了，建议与学校沟通，让学校校准铃声时间

直接输数值不好吗……
