### ISSUE TITLE
建议支持面板一键隐藏及关闭

### ISSUE THREAD

**Issue by bingsunny0730** [STBBRD/ZongziTEK-Blackboard-Sticker#32]
设计还行的，但有几点体验不是很好：

1.关闭并退出软件窗口需要到设置中才能关闭，而且 _确认关闭窗口_ 每次强行提醒3次，太过麻烦了，能否改为在部件面板直接显示关闭符号并一次性退出或系统图标托盘右键退出？
2.既然是贴边显示部件为何不增加可以 _自动贴边隐藏_ 的功能？或者点击系统托盘图标显示或隐藏部件，类似QQ面板的逻辑
3.课程表标题无法更改，可否加个重命名适合其它用途，如当作日程表之类
4.白板画笔粗细无法调整，能否加上？

**Comment by STBBRD** [comment]
感谢支持。将会加上画笔粗细调节功能，其它不考虑
