### ISSUE TITLE
简约模式下调整缩放会改变黑板贴宽度

### ISSUE THREAD

**Issue by PrefacedCorg** [STBBRD/ZongziTEK-Blackboard-Sticker#33]
在4k分辨率 系统缩放300%的情况下
课程表在缩放1.2 字体为18时
没重启一次 字体缩小一圈

**Comment by PrefacedCorg** [comment]
我又测试了一下 和 课程表的字体大小 缩放没太大关系
凡是系统缩放高都会错误
![image](https://github.com/user-attachments/assets/8c6e9a84-bf7e-4c94-8db2-5a68213be843)

**Comment by PrefacedCorg** [comment]
![image](https://github.com/user-attachments/assets/6fe948da-d9c6-4a33-b6f6-8257d1ac8086)
![image](https://github.com/user-attachments/assets/acae5039-7516-4b7c-b090-8cf423bfaa9f)

**Comment by STBBRD** [comment]
感谢反馈，将会尝试复现与修复

**Comment by STBBRD** [comment]
无法复现，请提供更加具体的问题描述
我尝试将缩放调大后多次重启黑板贴，字没有“每重启一次就变小一圈”

**Comment by PrefacedCorg** [comment]
e

**Comment by PrefacedCorg** [comment]
> 无法复现，请提供更加具体的问题描述 我尝试将缩放调大后多次重启黑板贴，字没有“每重启一次就变小一圈”

分辨率 3840*2160 系统缩放300% 课程表缩放1.2 课程表字号18

**Comment by PrefacedCorg** [comment]
或者是电脑每重启一次缩小一圈

**Comment by PrefacedCorg** [comment]
等我在回学校后进行屏幕录制

**Comment by STBBRD** [comment]
已解决
