### ISSUE TITLE
时间不同导致显示周几的课表错误

### ISSUE THREAD

**Issue by PrefacedCorg** [STBBRD/ZongziTEK-Blackboard-Sticker#34]
大部分学校的一体机都是使用 ops电脑
![image](https://tse4-mm.cn.bing.net/th/id/OIP-C.o5O--DUzzb3I5b1VfAVm0gHaHa?rs=1&pid=ImgDetMain)
而小部分里面的纽扣电池要么没有 要么没电 bios的时间不记录 只能在windows开机后通过网络自动同步时间
而在同步好之前 课程表已经启动 并且显示了不是今天的课表 需要手动调整
建议
![image](https://github.com/user-attachments/assets/d61e7eb7-4168-4277-adaf-591eb0311d6f)
可以实时调整

**Comment by STBBRD** [comment]
已修复
