### ISSUE TITLE
希望在简洁（看板）模式下可以让看板左右长一点或者可以自动换行

### ISSUE THREAD

**Issue by PrefacedCorg** [STBBRD/ZongziTEK-Blackboard-Sticker#35]
不然像广东这种天气 今天有雨，周三，周四，周五，周六，周日，周一将会下雨 时就啥也看不到了 而开启 完整 就挡了一半个桌面了

**Comment by STBBRD** [comment]
不可能出现。API 只返回 4 天

**Comment by PrefacedCorg** [comment]
6




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月17日(星期二) 晚上8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [STBBRD/ZongziTEK-Blackboard-Sticker] 希望在简洁（看板）模式下可以让看板左右长一点或者可以自动换行 (Issue #35)














 
不可能出现。API 只返回 4 天
