### ISSUE TITLE
希望在显示小黑板的界面中添加隐藏小黑板的按钮

### ISSUE THREAD

**Issue by dlam567** [STBBRD/ZongziTEK-Blackboard-Sticker#40]
希望在显示小黑板的界面中添加隐藏小黑板的按钮，有老师反馈小黑板占用面积比较大，切换为简约模式后，再打开小黑板会比较麻烦，感觉可以在工具栏中加入小黑板的图标按钮
[部分修改_ZongziTEK-Blackboard-Sticker-3.2.3.zip](https://github.com/user-attachments/files/17088061/_ZongziTEK-Blackboard-Sticker-3.2.3.zip)

**Comment by STBBRD** [comment]
小黑板占用面积较大是为了布置每科作业，若能被轻易隐藏，则容易出现自习课时作业不显示在屏幕上的问题
到底谁黑板的桌面图标能占用一半多的桌面啊

**Comment by dlam567** [comment]
问题与现状：
个人认为这个是有一定需求的，如果屏幕左侧图标太多的话，就会感觉整个屏幕都是满的。且有部分老师表示占用太大，想关闭或是折叠掉小黑板却找不到按钮。

建议：
可以加入一个比较小的按钮来切换状态这样也不会出现因为比较易于关闭而导致需要用的时候看不见，至于晚自习如果看不到的话，可以去点按钮，把小黑板给打开，又或者是说在晚自习的时候把状态定时调整一下，像是一个定时开关的功能。

以上只是一个个人小小的建议，无足轻重，只是希望能够被采纳，不是为了抬杠，希望小黑板可以越做越好

**Comment by STBBRD** [comment]
好的，感谢支持
