### ISSUE TITLE
BUG（语音播报）

### ISSUE THREAD

**Issue by lizhengyi3003** [STBBRD/ZongziTEK-Blackboard-Sticker#45]
无法播放语音，开启语音无反应。链接出现了问题？还是没有访问权？

**Comment by lizhengyi3003** [comment]
3.6新版本中对于天气的显示出现bug，无法显示天气。

**Comment by MKStoler4096** [comment]
> 3.6新版本中对于天气的显示出现bug，无法显示天气。

这个最好提到一个新工单里

**Comment by STBBRD** [comment]
> 无法播放语音，开启语音无反应。链接出现了问题？还是没有访问权？

最新版本已经修复
