### ISSUE TITLE
希望能够增加几个功能

### ISSUE THREAD

**Issue by xrgzs** [STBBRD/ZongziTEK-Blackboard-Sticker#5]
挺好的小工具，就是希望能够完善一下细节，根据实际需要，增加几个实用功能：

1. 课程表 增加 课前X分钟提醒应该干什么（最好支持自行填写，如课前3/5分钟提醒拿出课本、站起来读书等），方便适应某些学校特殊的管理需求
2. 课程表 增加 各个提醒项触发时播放自定义音频文件，以实现增强打铃的效果（最好支持分别设置播放哪个音频，如上课前5分钟播放铃声1，刚好上课时不播放/播放铃声2）
3. 课程表 增加 自定义各个提醒项[Blackboard-Notification-Service](https://github.com/STBBRD/Blackboard-Notification-Service)的提醒时间，能够加以延长（如延长到10s/30s）
4. 编辑启动台 完善 对已添加项目名称的重命名操作
5. 行为设置 增加 启动时默认关闭小黑板
6. 小黑板 增加 拖动标签自由调整横向大小，或增加按钮打开/收起小黑板
7. 小黑板 增加 锁定按钮，避免意外蹭到或故意乱画

**Comment by STBBRD** [comment]
感谢对本软件的支持
其中 3. 将在下一个版本实现，4. 和 7. 将在未来实现，其余与本软件目标不符，不会添加
