### ISSUE TITLE
编辑课程表时删除条目时会闪退

### ISSUE THREAD

**Issue by 114514emm** [STBBRD/ZongziTEK-Blackboard-Sticker#6]
版本	Windows 10 教育版
版本号	22H2
安装日期	‎6/‎1/‎2022
操作系统内部版本	19045.3570
体验	Windows Feature Experience Pack 1000.19052.1000.0
希沃一体机FC86ED

**Comment by STBBRD** [comment]
我试了好几遍，没复现出来，你用的是在 Releases 里面下载的正式版吗

**Comment by STBBRD** [comment]
已解决
