### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Little-Data** [STBBRD/ZongziTEK-Blackboard-Sticker#7]
- 字体可调节（包括时间日期），透明度可更改
- 小黑板可以收起，展开和全屏。功能方面参考`Ink Canvas 画板`
- 时间可以显示日期
- 提供退出软件方式，考虑使用托盘图标？
- 正在进行中的课程高亮显示，过长课程列表自动滚动

**Comment by STBBRD** [comment]
## 有些功能未来会有
- 调节透明度
- 课程旁边放置 "指示器"
## 有些功能不方便加
- 小黑板不用于课堂教学，而是用于布置作业、写通知的，和 Ink Canvas 画板针对的场景不同，不需要全屏
- 不考虑提供任何轻易退出软件的方式，不过你可以通过任务视图、Alt+F4 等方式退出软件，记住口诀 “是是否” 
- 未来将有一次布局大改，计划加入倒数日功能，并放在时间下面，因此放不下日期
